/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package azzamproyekdb01;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author Guest OSN
 */
public class EmployeeTableInterface extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeTableInterface
     */
    public EmployeeTableInterface() {
        initComponents();
        loadEmployees();
    }
    
    private Long employee_id;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnMenuReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAccessManager = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Nama", "Posisi", "Alamat", "Email", "No Telp."
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        btnAdd.setText("Tambah Data");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMenuReturn.setText("Kembali ke Menu");
        btnMenuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReturnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TABEL DATA KARYAWAN");

        btnAccessManager.setText("Cek Daftar Manajer");
        btnAccessManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessManagerActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus Data");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Perbarui Data");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Segarkan Tabel");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("Cari Karyawan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnMenuReturn)
                    .addComponent(btnAccessManager)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh)
                    .addComponent(jButton1))
                .addGap(0, 41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnAccessManager)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuReturn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        EmployeeDataInput dataInputFrame=new EmployeeDataInput();
        
        dataInputFrame.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMenuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReturnActionPerformed
        // TODO add your handling code here:
        AdminMenu admMenu=new AdminMenu();
        
        admMenu.setVisible(true);
        EmployeeTableInterface.this.setVisible(false);
    }//GEN-LAST:event_btnMenuReturnActionPerformed

    private void btnAccessManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessManagerActionPerformed
        // TODO add your handling code here:
        ManagerTableInterface manTable=new ManagerTableInterface();
        
        manTable.setVisible(true);
        EmployeeTableInterface.this.setVisible(false);
    }//GEN-LAST:event_btnAccessManagerActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblEmployee.getSelectedRow();
        if(selectedRow!=-1){
            String employeeId=tblEmployee.getValueAt(selectedRow, 0).toString();
            String employeeName = tblEmployee.getValueAt(selectedRow, 1).toString();  // Ambil nama karyawan dari kolom kedua
            String employeePosition = tblEmployee.getValueAt(selectedRow, 2).toString();  // Ambil posisi dari kolom ketiga
            String employeeAddress = tblEmployee.getValueAt(selectedRow, 3).toString();  // Ambil alamat dari kolom keempat
            String employeeEmail = tblEmployee.getValueAt(selectedRow, 4).toString();  // Ambil email dari kolom kelima
            String employeePhone = tblEmployee.getValueAt(selectedRow, 5).toString();
            EmployeeUpdate emp=new EmployeeUpdate(employeeId, employeeName,
                    employeePosition, employeeAddress,
                    employeeEmail, employeePhone);
        emp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Karyawan yang ingin diperbarui!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadEmployees();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblEmployee.getSelectedRow();
        if(selectedRow!=-1){
            String employee_id=tblEmployee.getValueAt(selectedRow, 0).toString();
            
            int confirm=JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus karyawan ini?", "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
            
            if(confirm==JOptionPane.YES_OPTION){
                try{
                    EmployeeAdmin emAdm=new EmployeeAdmin();
                    emAdm.deleteEmployee(employee_id);
                    loadEmployees();
                }catch(SQLException ex){
                    JOptionPane.showConfirmDialog(this, "Error saat menghapus karyawan "+ex, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Karyawan yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployeeSearch search=new EmployeeSearch();
        search.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeTableInterface().setVisible(true);
            }
        });
    }
    
    
    
    void loadEmployees(){
    // Tidak perlu memeriksa employee_id jika ingin memuat semua data
    DefaultTableModel tableModel = (DefaultTableModel) tblEmployee.getModel();
    tableModel.setRowCount(0);  // Bersihkan tabel sebelum memuat data baru

    String query = "SELECT employee_id, name, position, address, email, phone FROM EmployeeList ORDER BY employee_id";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query);
         ResultSet rs = pstmt.executeQuery()) {
        
        while(rs.next()){
            long employee_id = rs.getLong("employee_id");
            String employee_name = rs.getString("name");
            String position = rs.getString("position");
            String address = rs.getString("address");
            String email = rs.getString("email");
            String phone = rs.getString("phone");
            
            // Tambahkan data ke tabel
            Object[] row = {employee_id, employee_name, position, address, email, phone};
            tableModel.addRow(row);
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error saat memuat data karyawan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessManager;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMenuReturn;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
